#! /usr/bin/python
import rospy
from geometry_msgs.msg import Twist

pub = rospy.Publisher('/cmd_vel_mux/input/navi', Twist, queue_size=1)
rate = rospy.Rate(2)

def move(radi):
    rospy.init_node('noder')
    move = Twist() 
    move.linear.x = 0.1 
    move.angular.z = 0.1//radi

while not rospy.is_shutdown(): 
    pub.publish(move)
    rate.sleep()  



def listening():
    rospy.init_node("node3")
    rospy.Subscriber("/radius",int,move)
    rospy.spin()


if __name__ == '__main__':
    listening()





  