#!/usr/bin/python
import rospy
from std_msgs.msg import String

def node1():
    message_pub=rospy.Publisher("/hello",String,queue_size=10)
    rospy.init_node("node1")
    msg1=String()
    msg1.data="Hello"
    rate = rospy.Rate(0.5)

    while not rospy.is_shutdown():
        message_pub.publish(msg1) 
        print(msg1)
        rate.sleep()
if __name__ == '__main__':
    try:
        node1()
    except rospy.ROSInterruptException:
        pass