#!/usr/bin/python
import rospy
from std_msgs.msg import String

def talk():
    message_pub=rospy.Publisher("/world",String,queue_size=10)
    rospy.init_node("node2")
    msg1=String()
    msg1.data="World"
    rate = rospy.Rate(0.5)

    while not rospy.is_shutdown():
        message_pub.publish(msg1) 
        print(msg1)
        rate.sleep()
if __name__ == '__main__':
    try:
        talk()
    except rospy.ROSInterruptException:
        pass