#!/usr/bin/python
#import random
import rospy
from std_msgs.msg import String

def radpub():
    message_pub=rospy.Publisher("/radius",String,queue_size=10)
    rospy.init_node("noderpb")
    #msg1=String(random.randint(5, 10))
    msg1=String()
    msg1.data="5"
    rate = rospy.Rate(0.5)

    while not rospy.is_shutdown():
        message_pub.publish(msg1) 
        print(msg1)
        rate.sleep()
if __name__ == '__main__':
    try:
        radpub()
    except rospy.ROSInterruptException:
        pass