#!/usr/bin/python
import rospy
from std_msgs.msg import String

data2="String"

def listen2(data):
    global data2
    data2=data.data


def listen1(data):

    rospy.Subscriber("/world", String, listen2)
    print(data.data+data2)

#rate = rospy.Rate(1)


def listening():
    rospy.init_node("node3")
    rospy.Subscriber("/hello", String, listen1)
    # rate.sleep()
    
    rospy.spin()


if __name__ == '__main__':
    listening()
